name: Update derived repositories

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  template-sync:
    if: github.actor != 'dependabot[bot]' && github.repository == 'forgingblazor/template-base'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: ahmadnassri/action-template-repository-sync@v2.6.3
        with:
          github-token: ${{ secrets.TEMPLATE_SYNC }}
          dry-run: false
          skip-ci: true
