name: Update LICENSE file

on:
  schedule:
    - cron: '0 6 1 1 *'
  workflow_dispatch:

jobs:
  run:
    name: Validate
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - uses: FantasticFiasco/action-update-license-year@v3.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prTitle: 'chore: Updated LICENSE'
        commitTitle: 'chore: Updated LICENSE [skip ci]'
